/*
 * M4Version.hh
 *
 *  Generated by cmake from M4Version.hh.in
 *
 *  Created on: Apr 12, 2023
 *      Author: N.S. Oblath
 */

#ifndef M4VERSION_HH_
#define M4VERSION_HH_

#include "M4Constants.hh"

#include "scarab_version.hh"

namespace monarch4
{
    class M4_API M4Version : public scarab::version_semantic
    {
        public:
            M4Version();
            ~M4Version();
    };
}

#endif /* M4VERSION_HH_ */
