/*
 * M3Version.hh
 *
 *  Generated by cmake from M3Version.hh.in
 *
 *  Created on: Mar 20, 2013
 *      Author: nsoblath
 */

#ifndef M3VERSION_HH_
#define M3VERSION_HH_

#include "M3Constants.hh"

#include "scarab_version.hh"

namespace monarch3
{
    class M3_API M3Version : public scarab::version_semantic
    {
        public:
            M3Version();
            ~M3Version();
    };
}

#endif /* M3VERSION_HH_ */
